### ISSUE TITLE
3500 worldsize grid off by 1

### ISSUE THREAD

**Issue by MrKraken** [Substrata1/Inbound#1]
Recently switched from 4500 to 3500 worldsize and the grid number was off by 1 for supply drop location. The /grid plugin that it's based off of, works for reporting grid position for player.

As a quick and dirty fix, I just added +1 to the grid string.
`string Grid = $"{GetGridLetter((int)(x))}{z+1}";`

**Comment by Substrata1** [comment]
Sorry, just saw this (6 months later). Unfortunately, the flaws in the grid system itself are causing this, but there will be a manual grid offset option in the next version (0.6.0) that should correct this. That's the best solution we're going to get until Facepunch fixes it on their end.
